name: BalanceBridge
id: balancebridge
version: 0.1.0
category: Bitcoin
port: 3829
path: /
compose:
  services:
    balancebridge:
      image: balancebridge:latest
      ports:
        - "3829:3829"
      volumes:
        - data:/data
      environment:
        UMBREL_APP_DATA_DIR: /data
        UMBREL_APP_ID: balancebridge
  volumes:
    data:

