name: BalanceBridge
id: balancebridge
version: 0.1.0
category: Bitcoin
icon: icon.png
path: /

compose:
  services:
    balancebridge:
      image: ghcr.io/zndtoshi/balancebridge:latest
      ports:
        - "3829:3829"
      volumes:
        - data:/data
      environment:
        UMBREL_APP_DATA_DIR: /data
        UMBREL_APP_ID: balancebridge

volumes:
  data: